version: "3.9"

services:
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=mina0825@easv365.dk
      - RABBITMQ_DEFAULT_PASS=CIRkeline2

  game-master:
    build:
      context: .
      dockerfile: GameMasterService/Dockerfile
    image: annechristensen1995/rps-game-master:${DEPLOY_NUMBER}
    depends_on:
      - seq
      - zipkin
      - rmq

  copy-player:
    build:
      context: .
      dockerfile: CopyPlayerService/Dockerfile
    image: annechristensen1995/rps-copy-player:${DEPLOY_NUMBER}
    depends_on:
      - seq
      - zipkin
      - rmq

  random-player:
    build:
      context: .
      dockerfile: RandomPlayerService/Dockerfile
    image: annechristensen1995/rps-random-player:${DEPLOY_NUMBER}
    depends_on:
      - seq
      - zipkin
      - rmq